import { LuxuryColors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';

export const mainScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: LuxuryColors.background,
  },
  backgroundGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  goldOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: '40%',
  },
  splitDarkSection: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '60%',
    height: '100%',
    opacity: 0.15,
  },
  goldTransition: {
    position: 'absolute',
    left: '45%',
    top: 0,
    width: '30%',
    height: '100%',
    opacity: 0.8,
  },
  eliteAccent: {
    position: 'absolute',
    top: -100,
    right: -100,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: LuxuryColors.eliteAccentBg,
    shadowColor: LuxuryColors.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 50,
    elevation: 8,
  },
  luxuryCorner: {
    position: 'absolute',
    bottom: -50,
    left: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    shadowColor: '#6B4E00',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 25,
    elevation: 6,
  },
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LuxuryColors.surface,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LuxuryColors.border,
    shadowColor: LuxuryColors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  refreshButtonLoading: {
    opacity: 0.6,
    borderColor: LuxuryColors.textLight,
  },
  refreshButtonText: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.accent,
    marginLeft: 6,
  },
  refreshButtonTextLoading: {
    color: LuxuryColors.textLight,
  },
  appName: {
    fontSize: 32,
    fontFamily: 'Inter-ExtraBold',
    color: LuxuryColors.primary,
    marginBottom: 2,
    textShadowColor: 'rgba(212, 175, 55, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  profileButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: LuxuryColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileInitial: {
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.secondary,
  },
  propertyLocation: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
  },
  pricingCard: {
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 28,
    marginBottom: 32,
    shadowColor: LuxuryColors.shadowDark,
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.6,
    shadowRadius: 35,
    elevation: 25,
    borderWidth: 3,
    borderColor: LuxuryColors.goldBorder,
  },
  pricingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  pricingTitle: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.secondary,
  },
  pricingGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceItem: {
    alignItems: 'center',
  },
  priceValue: {
    fontSize: 28,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.secondary,
    marginBottom: 6,
  },
  suggestedPrice: {
    color: LuxuryColors.accent,
    fontSize: 32,
  },
  priceLabel: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textLight,
  },
  suggestedLabel: {
    color: LuxuryColors.accent,
  },
  section: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 22,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.primary,
  },
  dayContainer: {
    marginHorizontal: 20,
    marginBottom: 12,
  },
  dayItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#B8860B',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 15,
  },
  dayItemExpanded: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomWidth: 0,
  },
  dayLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  dateInfo: {
    marginRight: 20,
    alignItems: 'center',
    minWidth: 40,
  },
  dayName: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dateNumber: {
    fontSize: 24,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.accent,
    marginTop: 2,
  },
  priceInfo: {
    flex: 1,
  },
  priceFlow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  currentPrice: {
    fontSize: 20,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    marginRight: 8,
  },
  trendIcon: {
    marginHorizontal: 6,
  },
  suggestedPriceHighlight: {
    fontSize: 22,
    fontFamily: 'Inter-Bold',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: 'hidden',
  },
  goldGlow: {
    color: LuxuryColors.accent,
    backgroundColor: LuxuryColors.goldGlowBg,
    shadowColor: LuxuryColors.accent,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: LuxuryColors.goldGlowBorder,
  },
  expandedContent: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginTop: 0,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: '#B8860B',
  },
  aiTakeCard: {
    padding: 20,
    borderRadius: 16,
    margin: 16,
    marginBottom: 8,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
    borderWidth: 2,
    borderColor: '#B8860B',
  },
  aiTakeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  aiTakeTitle: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.accent,
    marginLeft: 8,
  },
  aiTakeText: {
    fontSize: 15,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    lineHeight: 22,
  },
  quickStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 8,
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    fontSize: 20,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.primary,
    marginBottom: 4,
  },
  suggestedStat: {
    color: LuxuryColors.accent,
  },
  statLabel: {
    fontSize: 11,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
  },
  suggestedStatLabel: {
    color: LuxuryColors.accent,
  },
  actionSection: {
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 40,
  },
  primaryButton: {
    borderRadius: 16,
    paddingVertical: 22,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    elevation: 20,
    borderWidth: 2,
    borderColor: '#6B4E00',
  },
  primaryButtonText: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.secondary,
  },
  // Loading skeleton styles
  skeletonText: {
    backgroundColor: LuxuryColors.border,
    borderRadius: 4,
  },
  skeletonSmall: {
    width: 40,
    height: 12,
    marginVertical: 2,
  },
  skeletonMedium: {
    width: 80,
    height: 16,
    marginVertical: 2,
  },
  skeletonLarge: {
    width: 120,
    height: 20,
    marginVertical: 2,
  },
  // Loading screen styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  loadingTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  loadingText: {
    fontSize: 16,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    marginLeft: 12,
  },
  // Simple loading dots styles
  loadingDotsContainer: {
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 8,
    paddingVertical: 8,
  },
  loadingDotsText: {
    fontSize: 18,
    color: LuxuryColors.accent,
    fontFamily: 'Inter-Medium',
    letterSpacing: 4,
  },
  loadingIndicatorText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textLight,
    textAlign: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  updateSection: {
    padding: 20,
    borderRadius: 16,
    marginTop: 16,
    marginBottom: 20,
    backgroundColor: LuxuryColors.surface,
  },
  updateSectionTitle: {
    fontSize: 18,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.primary,
    marginBottom: 16,
  },
  updateButton: {
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: LuxuryColors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  updateButtonDisabled: {
    opacity: 0.6,
  },
  aiUpdateButton: {
    // Style applied via LinearGradient
  },
  customUpdateButton: {
    // Style applied via LinearGradient
    marginBottom: 0,
    height: 48,
  },
  customPriceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  customPriceInputDisabled: {
    backgroundColor: LuxuryColors.surfaceDark,
    opacity: 0.6,
  },
  updateButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    minWidth: 120,
  },
  updateButtonIcon: {
    marginRight: 8,
  },
  updateButtonText: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
  },
  aiUpdateButtonText: {
    color: LuxuryColors.secondary,
  },
  customUpdateButtonText: {
    color: LuxuryColors.accent,
  },
  // Error state styles
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  errorButtonContainer: {
    marginTop: 32,
    width: '100%',
    maxWidth: 280,
  },
  secondaryButton: {
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: LuxuryColors.accent,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.accent,
  },
  customWindowSection: {
    marginTop: 40,
    marginBottom: 20,
  },
  customWindowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  toggleButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: LuxuryColors.goldGlowBg,
  },
  customWindowContent: {
    paddingHorizontal: 20,
  },
  dateSelectionSummary: {
    backgroundColor: LuxuryColors.surface + '20',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: LuxuryColors.accent + '30',
  },
  selectorLabel: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    marginBottom: 4,
  },
  selectedDatesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  dateDisplay: {
    flex: 1,
    alignItems: 'center',
  },
  dateDisplayLabel: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    marginBottom: 4,
  },
  dateDisplayValue: {
    fontSize: 16,
    fontFamily: 'Inter-Bold',
    color: LuxuryColors.accent,
  },
  dateRangeSummary: {
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: LuxuryColors.accent + '20',
  },
  dateRangeSummaryText: {
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
  },
  clearButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: LuxuryColors.textLight + '20',
  },
  clearButtonText: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
  },
  calendarToggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LuxuryColors.goldGlowBg,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: LuxuryColors.accent + '30',
  },
  calendarToggleText: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.accent,
    marginHorizontal: 8,
  },
  calendarContainer: {
    backgroundColor: LuxuryColors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: LuxuryColors.accent + '30',
    shadowColor: LuxuryColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  calendar: {
    borderRadius: 12,
  },
  calendarInstruction: {
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.textSecondary,
    textAlign: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: LuxuryColors.accent + '20',
  },
  loadCustomButton: {
    backgroundColor: LuxuryColors.accent,
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: LuxuryColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  loadingButton: {
    backgroundColor: LuxuryColors.textLight,
  },
  loadButtonText: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.surface,
    marginLeft: 8,
  },
  loadingButtonText: {
    color: LuxuryColors.textSecondary,
  },
  customDaysTitleContainer: {
    backgroundColor: LuxuryColors.surface + '20',
    borderRadius: 8,
    padding: 12,
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: LuxuryColors.accent + '20',
  },
  customDaysTitle: {
    fontSize: 16,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.textSecondary,
    textAlign: 'center',
  },
  actionButtons: {
    gap: 12,
    marginTop: 16,
  },
  actionButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  aiButton: {
    marginBottom: 8,
  },
  gradientButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  aiButtonText: {
    fontSize: 14,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.surface,
    marginLeft: 6,
  },
  customPriceSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  customPriceInput: {
    flex: 1,
    backgroundColor: LuxuryColors.surface + '20',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    fontFamily: 'Inter-Medium',
    color: LuxuryColors.text,
    borderWidth: 1,
    borderColor: LuxuryColors.accent + '30',
  },
  customButton: {
    backgroundColor: LuxuryColors.accent + '20',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: LuxuryColors.accent,
  },
  customButtonText: {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    color: LuxuryColors.accent,
  },
}); 